### ISSUE TITLE
Sta meerdere klachten toe

### ISSUE THREAD

**Issue by bartvandijk-cinq** [cinqict/safeplace-issue-tracker#2]
Na "anoniem inloggen" te hebben gedaan kon ik een klacht aanmaken.
Dit was daarmee meteen de enige klacht die ik actief kon hebben.
Aanmaken van een nieuwe klacht betekende de oude klacht verwijderen.
Misschien is een overzicht van actieve en afgeronde klachten fijn als landingspagina, en vanaf daar de mogelijkheid om een nieuwe klacht aan te maken.

**Comment by boukenijhuis-cinq** [comment]
Bedankt voor de feedback.

Dit is inderdaad één van de features die we op het lijstje hebben staan. We hebben nu bewust gekozen voor één klacht voor de MVP versie van het platform.
