### ISSUE TITLE
Login screen: Login anonymous does not seem to work

### ISSUE THREAD

**Issue by Testley** [cinqict/safeplace-issue-tracker#5]
ios versie: 18.1.1
Iphone SE

pre condition: After installation I enabled push notifications at first opening

Situation: Login anonymous

ER: Login in order to add a complaint
AR:  login spinning wheel stays on screen forevaaaah

<img width="212" alt="image" src="https://github.com/user-attachments/assets/d2854ae7-e0ca-463f-86fc-ad9bc7c1367a">

**Comment by Testley** [comment]
ios versie: 18.1.1
Iphone SE

**Comment by boukenijhuis-cinq** [comment]
Hi Testley! (goede naam 🥳 )

Bedankt voor het melden. Er was inderdaad iets stuk. Gisteravond is er een nieuwe versie van de app gepubliseerd en nu zou het inloggen weer moeten werken.

Bedankt voor het melden!
